# Generated by Django 6.0.1 on 2026-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_usermembership_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
