# Generated by Django 6.0.1 on 2026-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
