# Generated by Django 6.0.1 on 2026-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_usermembership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='username',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
